"""empty message

Revision ID: 4f1a9f858bb3
Revises: 
Create Date: 2018-07-07 08:34:23.626693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f1a9f858bb3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_category',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('isDelete', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_info',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('isDelete', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('avatar', sa.String(length=50), nullable=True),
    sa.Column('nick_name', sa.String(length=20), nullable=True),
    sa.Column('signature', sa.String(length=200), nullable=True),
    sa.Column('public_count', sa.Integer(), nullable=True),
    sa.Column('follow_count', sa.Integer(), nullable=True),
    sa.Column('mobile', sa.String(length=11), nullable=True),
    sa.Column('password_hash', sa.String(length=200), nullable=True),
    sa.Column('gender', sa.Boolean(), nullable=True),
    sa.Column('isAdmin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news_info',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('isDelete', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pic', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=30), nullable=True),
    sa.Column('summary', sa.String(length=200), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('click_count', sa.Integer(), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('reason', sa.String(length=100), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['news_category.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_user_author',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user_info.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_info.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'author_id')
    )
    op.create_table('news_comment',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('isDelete', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('msg', sa.String(length=200), nullable=True),
    sa.Column('news_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['news_comment.id'], ),
    sa.ForeignKeyConstraint(['news_id'], ['news_info.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_news_collect',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['news_info.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_info.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'news_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_news_collect')
    op.drop_table('news_comment')
    op.drop_table('tb_user_author')
    op.drop_table('news_info')
    op.drop_table('user_info')
    op.drop_table('news_category')
    # ### end Alembic commands ###
